### ISSUE TITLE
Key is generated in wrong way :(

### ISSUE THREAD

**Issue by starius** [wsddn/go-ecdh#3]
Function [GenerateKey](https://github.com/wsddn/go-ecdh/blob/3bd840ebec69a75dde08e1b2097cc01f790ea9c1/curve25519.go#L20) returns 32 random bytes. It does not apply further steps, described [here](http://cr.yp.to/ecdh.html):

```
     mysecret[0] &= 248;
     mysecret[31] &= 127;
     mysecret[31] |= 64;
```

**Comment by wsddn** [comment]
Issue should be fixed, thanks for reporting.

I have also added a disclaimer about the dangers of using this library.

**Comment by starius** [comment]
The private key should be modified before  generating public key from it.

> I have also added a disclaimer about the dangers of using this library.

Surprisingly this implementation has the most number of stars on github, which means that it is used more than other implementations. I wish DH functions were a part of curve25519 package not to invent a wheel many times.

**Comment by wsddn** [comment]
> The private key should be modified before generating public key from it.

My mistake sorry about that, its been about 2 years since implementing this and reading the literature. This should be okay now?

> Surprisingly this implementation has the most number of stars on github, which means that it is used more than other implementations

This comes as a bit of a surprise to me too, in hindsight the disclaimer should've been added right from the start. My bad.

**Comment by starius** [comment]
> This should be okay now?

Looks good to me. Disclaimer: I not a cryptographer.
